events {}

http {
  server {
    listen 6300;
    client_max_body_size 256m;

    location / {
      proxy_pass http://proof-server:6300;
      proxy_http_version 1.1;
      proxy_read_timeout 600s;
      proxy_send_timeout 600s;

      add_header Access-Control-Allow-Private-Network "true" always;
    }
  }
}
